### PR TITLE
Removes 'Remux' search on KG

### PR DESCRIPTION
**Pull request by Purfview**
Remuxes are prohibited on KG

### CODE REVIEW

**Comment by techmovie** [comment]
Remux is not allowed in KG ?

**Comment by Purfview** [comment]
Yes.

**Comment by techmovie** [comment]
Got it.
I wander know if you have installed the node_modules by `yarn`  command. cuz your commit message is not followed the rules I setted in this  project.

**Comment by Purfview** [comment]
I edit directly on GitHub's website.
And I don't code on your modular project, I work directly on `easy-seed.user.js `.
I don't use any fancy tools, just Notepad, so obviously nothing can be installed there.

**Comment by techmovie** [comment]
That's okay anyway.But your commit message should follow the simple rules below. Or your commits will not be included in Release info or changelog.md.

```
feat: (new feature for the user, not a new feature for build script)
fix: (bug fix for the user, not a fix to a build script)
docs: (changes to the documentation)
style: (formatting, missing semi colons, etc; no production code change)
refactor: (refactoring production code, eg. renaming a variable)
test: (adding missing tests, refactoring tests; no production code change)
chore: (updating grunt tasks etc; no production code change)
```

**Comment by Purfview** [comment]
Got it. So this edit should be `chore` or `fix`?

**Comment by techmovie** [comment]
I prefer `fix`.
I have merged this one,next time you should add the prefix.
Anyway,thank you for your contribution.

**Pull request merged**
