### PR TITLE
Replaces lookback regex (to support non-Chromium browsers)

### PR DESCRIPTION
**Pull request by Purfview**

### CODE REVIEW

**Comment by techmovie** [comment]
`48|57|72|10|21` only considers resolution.

Result of `40.2017.1080p.WEB-DL.5.1.H264-ascendance` should be `40 2017 1080p WEB-DL 5.1 H.264-ascendance`

image

**Comment by Purfview** [comment]
`.5.1` is invalid tag, no need to worry about invalid tags.

**Comment by techmovie** [comment]
It's pretty common in  remux file, like  Fallen.Angels.1995.1080p.BluRay.DTSHD-MA.5.1.AVC.Remux.mkv

**Comment by techmovie** [comment]
Forgot to say `4K` should be included.
Here's mine.
 `title.replace(/\.(?!(\d+))/ig, " ").replace(/\.(?=\d{4}|72|48|57|21|4k|(1|2|4|5|6|7)\.\d)/ig, '  ')`.

**Comment by Purfview** [comment]
Added `2K ` too, `21 ` `10` not needed as already covered by `\d{4}`.

**Pull request merged**
