### PR TITLE
Changed jquery link to  https://cdn.staticfile.org

### PR DESCRIPTION
**Pull request by Purfview**
I was banned on bootcss.com just  by trying to install the script few times in a row.
On the original host there is no such limitations.

### CODE REVIEW

**Comment by techmovie** [comment]
jquery.com doesn't work very well  in most parts of China.
image
I'll find perfect one and replace it.
Sorry for that I have to close this merge for now.

**Comment by Purfview** [comment]
Test how it works from google libs:

http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js

**Comment by techmovie** [comment]
@Purfview Google is blocked in China.😂

**Comment by Purfview** [comment]
Wait, really, even googleapis.com?! :D

**Comment by techmovie** [comment]
> Wait, really, even googleapis.com?! :D

It's a damn fact.

**Comment by Purfview** [comment]
Found jQuery min v1.11.1 on Greasyfork libs:

https://greasyfork.org/scripts/24686-jquery-min/code/jquerymin.js

**Comment by techmovie** [comment]
@Purfview //upcdn.b0.upaiyun.com/libs/jquery/jquery-1.7.1.min.js
https://cdn.staticfile.org/jquery/1.7.1/jquery.min.js
These two both work. just fine,you can have a test.

**Comment by Purfview** [comment]
Works fine: https://cdn.staticfile.org/jquery/1.7.1/jquery.min.js

**Comment by techmovie** [comment]
@Purfview Great,we can replace with this one. https://greasyfork.org/scripts/24686-jquery-min/code/jquerymin.js is not a good choice for our place.😑

**Comment by techmovie** [comment]
It's wired that commitlint didn't work.Commit messages should meet the [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/).
Next time when you submit commits, you should use `yarn commit` command.
Thank you for your PR.♥️

**Comment by Purfview** [comment]
I've no idea what that means. I made separate PR but GitHub for some reason put it here.

Btw I don't use any fancy tools, I code on Notepad and add changes directly on GitHub's website.

PS:
Looks like you found a way to merge. Do you want me to commit to master or some other branch?

**Comment by techmovie** [comment]
> Do you want me to commit to master or some other branch?
Just PR is okay.
But you should commit in terminal or sth with `yarn commit` command if you have executed the `yarn` command.

**Pull request merged**
